// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: football_square_games.sql

package db

import (
	"context"
	"database/sql"
)

const createFootballSquareGame = `-- name: CreateFootballSquareGame :execresult
INSERT INTO football_square_games (
  game_id, square_id, row_index, column_index
) VALUES (
  ?, ?, ?, ?
)
`

type CreateFootballSquareGameParams struct {
	GameID      sql.NullInt32
	SquareID    sql.NullInt32
	RowIndex    sql.NullInt32
	ColumnIndex sql.NullInt32
}

func (q *Queries) CreateFootballSquareGame(ctx context.Context, arg CreateFootballSquareGameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFootballSquareGame,
		arg.GameID,
		arg.SquareID,
		arg.RowIndex,
		arg.ColumnIndex,
	)
}
