// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateSquare(ctx context.Context, arg CreateSquareParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
