// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: squares.sql

package db

import (
	"context"
	"database/sql"
)

const createSquare = `-- name: CreateSquare :execresult
INSERT INTO squares (
  square_guid, square_size
) VALUES (
  ?, ?
)
`

type CreateSquareParams struct {
	SquareGuid string
	SquareSize sql.NullInt32
}

func (q *Queries) CreateSquare(ctx context.Context, arg CreateSquareParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSquare, arg.SquareGuid, arg.SquareSize)
}
